# App metadata; see https://appfair.net/#App.yml

# Fastlane metadata keys:
# https://docs.fastlane.tools/actions/deliver/#non-localized-metadata
# Note: localized keys for app title, subtitle, description, etc.
# should defined in localized resources instead of here:
# Sources/App/Resources/*.lproj/Localizable.strings
app:
  primary_category: 'UTILITIES'
  secondary_category: 'PRODUCTIVITY'

markets:
  #testflight: '0123456789'    # the assigned TestFlight id
  #appstore: '0123456789'      # the assigned App Store id
  #playstore: '123456543210'   # the assigned Play Store id

# Pages / Jekyll configuration::
remote_theme: appfair/fairapp-theme

<<<<<<< HEAD
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

encoding: utf-8
title: "The App Fair"
#logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
#description: "My Podcasts and Projects" # Site description and default description, also used in jekyll-seo-tag
url: "https://appfair.app" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/App-Fair/App"
email: "appfair@appfair.net"

social: # jekyll-seo-tag > social overrides
  name: The App Fair # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/TheAppFair
    - https://github.com/appfair
    - https://discord.gg/R4bFP8qpw7

social_links:
  Twitter: https://twitter.com/TheAppFair
  GitHub: https://github.com/appfair
  Discord: https://discord.gg/R4bFP8qpw7

# the app icon is generated from a simple SVG path and a tint color
#icon:
  # gradient tint color (symbolic name or "#RRGGBB")
  #tint: 'red'
  # SVG path to place in the center of the icon
  #path: 'M0 200 v-200 h200 a100,100 90 0,1 0,200 a100,100 90 0,1 -200,0 z'


