# App metadata; see https://appfair.net/#App.yml
app:
  #name: "App Name" # 30-char limit
  #subtitle: "A brief summary of the App" # 30-char limit
  #keywords: "appfair,free" # comma separated keywords ; 100-char limit
  #description: "A complete description of the app" # 4000-char limit
  #notes: "Some notes about this app for reviewers."

  # primary_category and secondary_category can be any of: FOOD_AND_DRINK, BUSINESS, EDUCATION, SOCIAL_NETWORKING, BOOKS, SPORTS, FINANCE, REFERENCE, GRAPHICS_AND_DESIGN, DEVELOPER_TOOLS, HEALTH_AND_FITNESS, MUSIC, WEATHER, TRAVEL, ENTERTAINMENT, STICKERS, GAMES, LIFESTYLE, MEDICAL, MAGAZINES_AND_NEWSPAPERS, UTILITIES, SHOPPING, PRODUCTIVITY, NEWS, PHOTO_AND_VIDEO, NAVIGATION

  primary_category: "UTILITIES" 
  secondary_category: "PRODUCTIVITY"


  # translations for the name, subtitle, description, and keywords
  # Supported language keys are: # ar-SA, ca, cs, da, de-DE, el, en-AU, en-CA, en-GB, en-US, es-ES, es-MX, fi, fr-CA, fr-FR, he, hi, hr, hu, id, it, ja, ko, ms, nl-NL, no, pl, pt-BR, pt-PT, ro, ru, sk, sv, th, tr, uk, vi, zh-Hans, zh-Hant

  localizations:
    #fr-FR:
    #  name: "App Name in French"
    #  subtitle: "App Subtitle in French"
    #  description: "App Description in French"

# marketplace-issued indentifiers for the distribution channels for this app
markets:
  testflight: "1644895985"    # the assigned TestFlight id
  # testflighturl: "https://testflight.apple.com/join/UQtz2PPT"  # the public TestFlight beta link (enabling this will auto-submit the TestFlight build for external release)
  #appstore: "0123456789"      # the assigned App Store id
  #appstoreurl: "https://…"    # the official App Store landing page
  #playstore: "123456543210"   # the assigned Play Store id

# Pages / Jekyll configuration:
remote_theme: "appfair/fairapp-theme"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

encoding: utf-8
title: "The App Fair"
#logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
#description: "My Podcasts and Projects" # Site description and default description, also used in jekyll-seo-tag
url: "https://appfair.app" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/App-Fair/App"
email: "appfair@appfair.net"

social: # jekyll-seo-tag > social overrides
  name: The App Fair # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/TheAppFair
    - https://github.com/appfair
    - https://discord.gg/R4bFP8qpw7

social_links:
  Twitter: https://twitter.com/TheAppFair
  GitHub: https://github.com/appfair
  Discord: https://discord.gg/R4bFP8qpw7

# the app icon is generated from a simple SVG path and a tint color
#icon:
  # gradient tint color (symbolic name or "#RRGGBB")
  #tint: 'red'
  # SVG path to place in the center of the icon
  #path: 'M0 200 v-200 h200 a100,100 90 0,1 0,200 a100,100 90 0,1 -200,0 z'


